sudo: false
language: ruby
rvm:
- 2.3.1
before_install: gem install bundler -v 1.16.1
deploy:
  provider: rubygems
  api_key:
    secure: uAVdVGZQ/FLaHWV36r5dIHOSkJPQUkarDDd6HnlUt1VTh/sIR6o6p3wXvAzUOncNwbBl/xyUTb5U4nc9JAOOfpMGWmZ+CfdIvMHcRAfwYEvWjkDlJs6NZlCNsds88QqQl5ZsHGQj2r28I26FV5oDCMVbZ7FS1gAWqcd4suiMoFXXUU+Bfp9qPSi6rfewkezTv7rmI7pp/LP+1rBcZLWdZncBLNgGPG6i1no4Whvj7Uq9KJpPe9i/p/CYPvw0Vc252O7C0d/qL3BnwkfhTkAVa4Z1mEWnXQD3IRIwJOC06C74rq/ryZ4dvZCwGJs2fIX963Rw/dCjWfrHm90eMWXdmUD9nXEKBDNDrjttd6Acsfz52u5f6sU7EbtlNPukwe4SevUNz/J1hCS+D3z+/T2BgACVOR0R6Ht9WPmj3NI72SijKpUh0zOIq0PuLfE410rdjXCkw1/FabhnbTtoJDgI61rg2ZQCVGWwzF9ciJ5o1p/kPayQVKW4R/EBKI+Gyz3ZyLYGNgW02zd1rW7KZa178nC2wW5tp7Wlaqqw8jS9DQYyBIsDGByAcUth8JCBmvjNg0krtzRDUrYeiuVMNl5PZ256KfTV6lMuobwBpkdyjBtQdscmKzwbhL9ej89QSeiwmOOE4fEzNSb4H7MKfQ0W8YI90PRnOJzgBoRBycjjtrw=
  gem: mumukit-assistant
  on:
    tags: true
    repo: mumuki/mumukit-assistant
